### ISSUE TITLE
Empty graphs and process list on Ubuntu Focal

### ISSUE THREAD

**Issue by BYK** [bvaisvil/zenith#121]
Hi!

I heard about Zenith and wanted to give it a try on a dev machine hosted on AWS EC2. It starts up without any apparent errors but all I get is empty charts and no process list at all. The UI is responsive, I just cannot get any of the info. Tried with `sudo` just in case, no change. Ran it in debug mode and here's the output: https://gist.github.com/BYK/cd9cbe4a0601fa8a654b0698b6e2fcf8

Happy to chip in if you can guide me in the right direction.

**Comment by BYK** [comment]
Sorry for the lack of response here! I don't get to see any process list at all. Not running in a container. All I get is something like this:
![image](https://user-images.githubusercontent.com/126780/184632439-bf0d8b15-1e4d-4dd2-a7b0-abd21f4d7a57.png)

**Comment by bvaisvil** [comment]
I think this may just be a matter of options and/or screen size. Pressing "F1" will give you an option to turn on/off different sections. Is the process section on? 
<img width="959" alt="Screen Shot 2022-08-17 at 10 46 57 AM" src="https://user-images.githubusercontent.com/3818351/185184332-7e5dd9ff-4bad-4319-ae01-4fb4304c13e2.png">

If it is you can try turning off some of the sections so that it has room to render in the screen dimensions your showing...

**Comment by BYK** [comment]
Aha, that worked! Not sure why the default state was weird tho :(
