### ISSUE TITLE
Rendering corruption with previous content on screen

### ISSUE THREAD

**Issue by UbiquitousPhoton** [bvaisvil/zenith#23]
It would seem that I ned to run clear prior to running Zenith, otherwise the formatting seems to become messed up. This appears to be an issue with it rendering over the text that was there before.

**Comment by bvaisvil** [comment]
This may also be related to the other issue you created, but let's keep them both open for now.

**Comment by UbiquitousPhoton** [comment]
Attaching images of corruption - this certainly seems to be the previous text.

![photo_2020-04-06_14-27-08](https://user-images.githubusercontent.com/39134173/78563421-d8c8bc80-7812-11ea-8200-f2f18f6ac3c5.jpg)
![photo_2020-04-06_14-27-23](https://user-images.githubusercontent.com/39134173/78563438-dd8d7080-7812-11ea-9d83-f5ebc8d228ed.jpg)

**Comment by bvaisvil** [comment]
Yes, I was not handling TTYs correctly. Since TTYs don't have an alternate screen, it just overwrites the existing one. 

This [commit](https://github.com/bvaisvil/zenith/commit/38dd259e301eb873ff9b896c04477d0f2a8bbfb2) should fix the problem by clearing the screen before the first render and restoring the cursor position and clearing after the last. In my testing, this fixed the issue.

I'm planning the next release now to fix a few issues and this will be one of them!

**Comment by bvaisvil** [comment]
Okay this should be fixed in the latest release: https://github.com/bvaisvil/zenith/releases/tag/0.8.2
