### ISSUE TITLE
Network and disk speeds are scaled up by the refresh rate

### ISSUE THREAD

**Issue by sumwale** [bvaisvil/zenith#64]
The network and disk speeds shown are scaled by the refresh rate (i.e. 2X for the default of 2000ms). This can be seen easily by starting a large download or disk copy, then starting zenith with refresh rate of 1000, then stopping and restarting with a larger one of say 5000. Both the histogram and the numbers will be seen to be scaled up by 5X.

Briefly looked at the code in CPUTimeApp.update_networks which uses data.get_received() and data.get_transmitted() to update the histogram but these are not rates rather the diff in total bytes since the last call to sysinfo's refresh_all. Similar issue must exist in disk rate updates.

Have not looked at the code very closely but from my quick reading so far, one clean solution to this might be to take care of this in HistogramMap which needs to take note of the metrics passed as rate per sec, and those that are raw values since the last update and need to be converted to rate. This looks a better approach since the histogram abstraction should understand the difference between the two kinds of values and may have its own policies (e.g. simple average for the duration or more elaborate ones in future). Alternatively it can always assume the passed value is rate per sec (like currently) and the callers need to take care of conversions.

**Comment by sumwale** [comment]
While looking at the code found another issue that HistogramMap stores the tick value in the database, so while re-using the previous database the old persisted tick value will get used. This might cause an issue in methods like render_top_title_bar that depend on that field from HistogramMap.

**Comment by bvaisvil** [comment]
Thank you very much for reporting this and for the PR. [I ended up deciding to address this issue slightly differently.](https://github.com/bvaisvil/zenith/commit/3f6a693b89b8f45ea333253de96aea0c8b2ffbfa)

As for the `HistogramMap` stored tick value - the intention was to use that value instead of the user supplied value in the case of a conflict - as the database value needs to be consistent throughout the entire histogram history to support some features. This wasn't actually the case in the code, but it is now.
