### ISSUE TITLE
Panic on WSL writing db

### ISSUE THREAD

**Issue by bvaisvil** [bvaisvil/zenith#7]
`thread '<unnamed>' panicked at 'Couldn't open database.: Io(Custom { kind: Other, error: "Os { code: 38, kind: Other, message: \"Function not implemented\" }" })', src/metrics.rs:248:17
thread '<unnamed>' panicked at 'Couldn't open database.: Io(Custom { kind: Other, error: "Os { code: 38, kind: Other, message: \"Function not implemented\" }" })', src/metrics.rs:248:17
thread panicked while panicking. aborting.
                                          Illegal instruction (core dumped)`

Seems to happen at the right write in the sled db.

**Comment by bvaisvil** [comment]
perhaps related to https://github.com/spacejam/sled/issues/958

**Comment by radix** [comment]
Just curious, is this happening in WSL or WSL2?

**Comment by bvaisvil** [comment]
Believe it is WSL as
` cmd.exe /c "systeminfo" | grep "^OS Version"`
gives me
 `OS Version:                10.0.18363 N/A Build 18363` 
and WSL2 is in build >= 18917 ?

**Comment by radix** [comment]
I see, yeah, I think so. `wsl -l -v` is another way to explicitly check if it's version 2.

FWIW wsl2 is actually a stock linux kernel running in a VM, instead of a reimplementation of Linux APIs on Windows, so it's much less likely to have incompatibilities.

If you can provide a binary (I don't see a windows executable for the latest release) I can test to see if this also happens on WSL2. No worries if that's not convenient for you though.

**Comment by radix** [comment]
Ok, it seems to work fine on WSL2!

**Comment by bvaisvil** [comment]
That's good. Thanks very much for testing that!

**Comment by bvaisvil** [comment]
Latest version has no issues in WSL for me. Feel free to re-open this if you find anything. Thanks!
