### ISSUE TITLE
Output / formatting broken on Apple Silicon

### ISSUE THREAD

**Issue by richiksc** [bvaisvil/zenith#94]
Here's the output of running Zenith 0.12.0b on an M1-based Mac:

![image](https://user-images.githubusercontent.com/8939680/104366973-c1280e00-54df-11eb-810f-2277fa15d75e.png)

As you can see, logs are leaving their windows and the charts are illegible.

This is the screenshot on the readme:

![image](https://github.com/bvaisvil/zenith/raw/master/assets/screenshot.png)

**Comment by bvaisvil** [comment]
I believe this is because `heim` library is outputting to stdout because it cannot parse the arm64 architecture, looks to be fixed in this commit: https://github.com/heim-rs/heim/pull/303

You could try changing the heim dependency in the[ Cargo.toml](https://github.com/bvaisvil/zenith/blob/master/Cargo.toml):
```heim = {git = "https://github.com/heim-rs/heim", branch="master", features = ["full"]}```

If you try that, please let me know if it fixes the issue!

**Comment by richiksc** [comment]
@bvaisvil, Yep, installing `heim` from `master` fixes the issue!

**Comment by bvaisvil** [comment]
Awesome! Thanks for testing! I'll update the `Cargo.toml` with that change.

**Comment by richiksc** [comment]
Do you know whether this change will be included in the 0.12.0.release? Do you need a new release from `heim` before you can release?

**Comment by bvaisvil** [comment]
Ideally there would be a new version of heim as I don't like using git dependencies if I can avoid it.

However, in this case I think it's best to have zenith working on M1 Macs, so I've released [0.12.0](https://github.com/bvaisvil/zenith/releases/tag/0.12.0).

**Comment by richiksc** [comment]
Thanks for the fix and the release!
